# Generated by Django 2.2.7 on 2019-11-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
    ]
